# Generated by Django 6.0.5 on 2026-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Тип файла'),
        ),
    ]
